# Generated by Django 3.1.4 on 2021-10-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureStatuses',
            new_name='FeatureStatus',
        ),
        migrations.RenameModel(
            old_name='FeatureTypes',
            new_name='FeatureType',
        ),
    ]
